name: GitHub Workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    uses: BrunoBrasolin/workflow-template/.github/workflows/nodejs-docker-ci.yml@main
    with:
      applicationName: api-log
    secrets: inherit

  CD:
    needs: CI
    uses: BrunoBrasolin/workflow-template/.github/workflows/nodejs-docker-cd.yml@main
    with:
      dockerAccount: brunobrasolin
      applicationName: api-log
      port: 84
    secrets: inherit